version: 0.2

phases:
  install:
    commands:
      - export IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export ACCOUNT=$(echo $CODEBUILD_BUILD_ARN |cut -f5 -d:)
      - export REPOSITORY_URI=048815747800.dkr.ecr.us-east-1.amazonaws.com/examp-examp-793dcbtqqe9j
      - echo '***** Installing shyaml:'
      - pip install shyaml
      - echo '***** This is the current env:'
      - printenv
      - echo '***** Logging in to ECR:'
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - echo '***** Retrieving Deploy Key:'
      - aws secretsmanager get-secret-value --region us-east-1 --secret-id codebuild-ssh-pub-key --query SecretString | tr -d '"' > ~/.ssh/id_rsa.pub
      - aws secretsmanager get-secret-value --region us-east-1 --secret-id codebuild-ssh-priv-key --query SecretString | sed 's/\\n/\n/g' | tr -d '"' > ~/.ssh/id_rsa
      - chmod 400 ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa.pub
      - echo '***** Configuring Git:'
      - echo '[user]' > ~/.gitconfig
      - echo '    name = codebuild ci' >> ~/.gitconfig
      - echo '    email = no@amway.com' >> ~/.gitconfig
      - echo '***** Cloning Config Repo:'
      - git clone git@github.com:brentlangston/eks-gitops.git $HOME/eks-gitops
  build:
    commands:
      - echo '***** Building Image:'
      - docker build -t example-api:latest .
      - echo '***** Tagging Image:'
      - docker tag example-api:latest ${REPOSITORY_URI}:${IMAGE_TAG}
      - docker tag example-api:latest ${REPOSITORY_URI}:latest
      - echo '***** Pushing Image:'
      - docker push ${REPOSITORY_URI}:${IMAGE_TAG}
      - docker push ${REPOSITORY_URI}:latest
      - printf '[{"name":"example-backend","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo $IMAGE_TAG > code_hash.txt
      - cd $HOME/eks-gitops/
      - pwd
      - ls
      - oldtag=$(cat magic/development/yellow-api/deployment.yaml | shyaml get-value spec.template.spec.containers.0.image | cut -f2 -d:)
      - sed -i "s/${oldtag}/${IMAGE_TAG}/" magic/development/yellow-api/deployment.yaml 
      - oldtag=$(cat magic/development/blue-api/deployment.yaml | shyaml get-value spec.template.spec.containers.0.image | cut -f2 -d:)
      - sed -i "s/${oldtag}/${IMAGE_TAG}/" magic/development/blue-api/deployment.yaml 
      - oldtag=$(cat magic/development/pink-api/deployment.yaml | shyaml get-value spec.template.spec.containers.0.image | cut -f2 -d:)
      - sed -i "s/${oldtag}/${IMAGE_TAG}/" magic/development/pink-api/deployment.yaml 
      - git add .
      - git commit -a -m "Updating deployment to $IMAGE_TAG tag"
      - git push
  post_build:
    commands:
artifacts:
  files:
    - '**/*'
