version: 0.2

phases:
  install:
    commands:
      - export IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export ACCOUNT=$(echo $CODEBUILD_BUILD_ARN |cut -f5 -d:)
      - export REPOSITORY_URI=048815747800.dkr.ecr.us-east-1.amazonaws.com/examp-examp-ew0c2u1ne7ai
      - echo '***** This is the current env:'
      - printenv
      - echo '***** Retrieving Deploy Key:'
      - aws secretsmanager get-secret-value --region us-east-1 --secret-id codebuild-ssh-pub-key --query SecretString | tr -d '"' > ~/.ssh/id_rsa.pub
      - aws secretsmanager get-secret-value --region us-east-1 --secret-id codebuild-ssh-priv-key --query SecretString | sed 's/\\n/\n/g' | tr -d '"' > ~/.ssh/id_rsa
      - chmod 400 ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa.pub
      - echo '[user]' > ~/.gitconfig
      - echo '    name = codebuild ci' >> ~/.gitconfig
      - echo '    email = no@amway.com' >> ~/.gitconfig
      - git clone git@github.com:brentlangston/eks-gitops.git
  build:
    commands:
      - sed -i "s/image: .*/image: $REPOSITORY_URI:$IMAGE_TAG/" eks-gitops/magic/development/yellow-api/deployment.yaml 
      - sed -i "s/image: .*/image: $REPOSITORY_URI:$IMAGE_TAG/" eks-gitops/magic/development/blue-api/deployment.yaml 
      - sed -i "s/image: .*/image: $REPOSITORY_URI:$IMAGE_TAG/" eks-gitops/magic/development/pink-api/deployment.yaml
      - cd eks-gitops
      - git add .
      - git commit -a -m "Updating deployment to $IMAGE_TAG tag"
      - git push
  post_build:
    commands:
      - # printf '[{"name":"example-backend","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - # echo $IMAGE_TAG > code_hash.txt

artifacts:
  files:
    - '**/*'
