version: 0.2

phases:
  install:
    commands:
      - export IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export ACCOUNT=$(echo $CODEBUILD_BUILD_ARN |cut -f5 -d:)
      - echo '***** This is the current env:'
      - printenv
      - echo '***** Logging in to ECR:'
      - # $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - # docker build -t examp-examp-ew0c2u1ne7ai .
  post_build:
    commands:
      - # printf '[{"name":"example-backend","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - # echo $IMAGE_TAG > code_hash.txt

artifacts:
  files:
    - '**/*'
